apiVersion: v1
kind: Service
metadata:
  name: ingestion
  namespace: woodpantry
  labels:
    app: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
